### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by rjw1**
To pick up the stable API of vCloud Core.

### CODE REVIEW

**Comment by mattbostock** [comment]
Should this be version 1.4.1 rather than 2.0.0?

**Comment by annashipman** [comment]
I agree with @mattbostock, I think it's should be; there's no breaking change in this tool itself. Same applies to https://github.com/gds-operations/vcloud-walker/pull/110, but that's been merged now so I suspect we'll just have to leave that.

**Comment by annashipman** [comment]
good spot @mattbostock

**Comment by rjw1** [comment]
So I did think about this and I decided that everything may as well get bumped to a new major version for no particular reason.
@dcarley and I discussed this on slack

```irc
16:51 <+dcarley> @bob: I wonder if walker and edge_gateway deserve a major bump? Since core 
                 hasn't changed in functionality.
16:53 <+bob> dcarley: yeah. i was wondering that
16:53 <+bob> however, i thought we should major bump eveything
16:55 <+bob> everything stable and startign on x.0.0
16:57 <+dcarley> I think if we do, we should add a note to CHANGELOGs to indicate that there 
                 aren't any functional changes in core.
```

Which @ajlanghorn missed before he merged gds-operations/vcloud-walker#110

So what do people want to do?

**Comment by ajlanghorn** [comment]
Personally, and given I already merged https://github.com/gds-operations/vcloud-walker/pull/110, I think we should merge them all and add a note in the CHANGELOGs.

**Comment by annashipman** [comment]
Let's stick to [semantic versioning](http://semver.org/). "MAJOR version when you make incompatible API changes". So this should be 1.4.1. Never mind about vCloud Walker – the versioning there is very much out of kilter anyway as it had progressed a long way before we started being strict about it.

**Pull request closed without merging**
