### PR TITLE
Fix multiple subnets

### PR DESCRIPTION
**Pull request by joshmyers**
We need to have multiple local_subnets and multiple peer_subnets. This PR enables that.

Requires: https://github.com/fog/fog/pull/3671

### CODE REVIEW

**Comment by mattbostock** [comment]
The tests are failing.

**Comment by joshmyers** [comment]
@mattbostock my bad, tests are now passing. We need to wait for fog/fog#3671 to be released.

**Comment by mattbostock** [comment]
:+1: Ready to merge once Fog have released a new version (and we've updated our dependencies on it).

**Comment by joshmyers** [comment]
@mattbostock Fog have pushed a new release. I've updated vcloud-core to pull it in:
https://github.com/gds-operations/vcloud-core/pull/176

**Comment by mattbostock** [comment]
@joshmyers: We'll need to bump the version of vcloud-core and update our dependency on vcloud-core in the [Gemspec](https://github.com/gds-operations/vcloud-edge_gateway/blob/a54c0c0063e89b7204e83b30156a26fc751b7f2b/vcloud-edge_gateway.gemspec#L24) file before we can use this feature.

**Pull request merged**
